In [13]:
import pandas as pd

In [21]:
tinder_data = pd.read_csv("../data/tinder_data_prepared.csv")

In [22]:
# check shape
tinder_data.shape

(1321, 58)

In [23]:
# check info
tinder_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1321 entries, 0 to 1320
Data columns (total 58 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   user_id                                1321 non-null   object
 1   age                                    1321 non-null   int64
 2   sex                                    1321 non-null   int64
 3   height                                 1321 non-null   float64
 4   education_level                        1321 non-null   float64
 5   dropped_out                            1321 non-null   int64
 6   drinks_desperately                     1321 non-null   bool
 7   drinks_not at all                      1321 non-null   bool
 8   drinks_often                           1321 non-null   bool
 9   drinks_rarely                          1321 non-null   bool
 10  drinks_socially                        1321 non-null   bool
 11  drinks_very often                      1321 non-null   bool
 12  drugs_never                            1321 non-null   bool
 13  drugs_often                            1321 non-null   bool
 14  drugs_sometimes                        1321 non-null   bool
 15  job_artistic / musical / writer        1321 non-null   bool
 16  job_banking / financial / real estate  1321 non-null   bool
 17  job_clerical / administrative          1321 non-null   bool
 18  job_computer / hardware / software     1321 non-null   bool
 19  job_construction / craftsmanship       1321 non-null   bool
 20  job_education / academia               1321 non-null   bool
 21  job_entertainment / media              1321 non-null   bool
 22  job_executive / management             1321 non-null   bool
 23  job_hospitality / travel               1321 non-null   bool
 24  job_law / legal services               1321 non-null   bool
 25  job_medicine / health                  1321 non-null   bool
 26  job_military                           1321 non-null   bool
 27  job_other                              1321 non-null   bool
 28  job_political / government             1321 non-null   bool
 29  job_rather not say                     1321 non-null   bool
 30  job_retired                            1321 non-null   bool
 31  job_sales / marketing / biz dev        1321 non-null   bool
 32  job_science / tech / engineering       1321 non-null   bool
 33  job_student                            1321 non-null   bool
 34  job_transportation                     1321 non-null   bool
 35  job_unemployed                         1321 non-null   bool
 36  smokes_no                              1321 non-null   bool
 37  smokes_sometimes                       1321 non-null   bool
 38  smokes_trying to quit                  1321 non-null   bool
 39  smokes_when drinking                   1321 non-null   bool
 40  smokes_yes                             1321 non-null   bool
 41  body_profile_a little extra            1321 non-null   bool
 42  body_profile_athletic                  1321 non-null   bool
 43  body_profile_average                   1321 non-null   bool
 44  body_profile_curvy                     1321 non-null   bool
 45  body_profile_fit                       1321 non-null   bool
 46  body_profile_full figured              1321 non-null   bool
 47  body_profile_jacked                    1321 non-null   bool
 48  body_profile_overweight                1321 non-null   bool
 49  body_profile_rather not say            1321 non-null   bool
 50  body_profile_skinny                    1321 non-null   bool
 51  body_profile_thin                      1321 non-null   bool
 52  body_profile_used up                   1321 non-null   bool
 53  new_languages_interested               1321 non-null   bool
 54  new_languages_not interested           1321 non-null   bool
 55  new_languages_somewhat interested      1321 non-null   bool
 56  likes_dog                              1321 non-null   int64
 57  likes_cats                             1321 non-null   int64
dtypes: bool(50), float64(2), int64(5), object(1)
memory usage: 147.2+ KB

In [24]:
tinder_data.head()

,user_id,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
0,fffe31003000,28,1,62.0,4.0,0,False,False,False,False,...,False,False,False,False,True,False,True,False,1,1
1,fffe31003200,24,0,65.0,3.0,0,False,False,False,False,...,False,False,False,False,False,True,False,False,1,1
2,fffe31003300,29,1,73.0,3.0,0,False,False,False,False,...,False,False,False,False,False,False,True,False,1,1
3,fffe31003400,33,0,65.0,4.0,0,False,False,False,False,...,False,False,False,False,False,False,True,False,0,0
4,fffe31003500,39,0,65.0,4.0,0,False,False,True,False,...,False,False,False,False,False,False,True,False,1,0

In [28]:
# set index
tinder_data = tinder_data.set_index("user_id")

In [29]:
tinder_data.head()

,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,drinks_socially,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
user_id,,,,,,,,,,,,,,,,,,,,,
fffe31003000,28,1,62.0,4.0,0,False,False,False,False,False,...,False,False,False,False,True,False,True,False,1,1
fffe31003200,24,0,65.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,1
fffe31003300,29,1,73.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,False,True,False,1,1
fffe31003400,33,0,65.0,4.0,0,False,False,False,False,True,...,False,False,False,False,False,False,True,False,0,0
fffe31003500,39,0,65.0,4.0,0,False,False,True,False,False,...,False,False,False,False,False,False,True,False,1,0

In [30]:
from sklearn.decomposition import TruncatedSVD 

# Apply SVD to the training data
svd = TruncatedSVD(n_components=20) 
# this is a matrix of all the profiles of the opposite gender
tinder_profiles_matrix = svd.fit_transform(tinder_data)

tinder_profiles_matrix

array([[ 6.81246999e+01,  1.84406016e+00, -3.91469382e-01, ...,
        -8.54875364e-02, -1.03044108e-01,  2.65165081e-01],
       [ 6.93214169e+01, -2.97741372e+00, -8.07475208e-01, ...,
        -6.15140878e-02, -4.86716924e-02, -6.92653765e-02],
       [ 7.86335479e+01, -1.51333216e+00, -1.09259725e-01, ...,
        -4.88736702e-02, -1.28916280e-01,  5.53051265e-02],
       ...,
       [ 7.90137430e+01, -6.12506336e-01, -1.27343442e-01, ...,
        -5.38158095e-02,  4.25567156e-01, -1.14167111e-01],
       [ 7.29681475e+01, -4.64923839e+00,  7.18356832e-01, ...,
         6.64198638e-02,  4.28522238e-02, -1.52673123e-01],
       [ 7.63881860e+01, -1.65619874e+00, -4.76758297e-02, ...,
        -5.65258579e-01,  5.79961073e-01,  4.01367172e-01]])

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tinder_profiles_matrix)

array([[1.        , 0.99646088, 0.99817833, ..., 0.99837779, 0.99494244,
        0.99785025],
       [0.99646088, 1.        , 0.99942894, ..., 0.99879413, 0.9992087 ,
        0.99895397],
       [0.99817833, 0.99942894, 1.        , ..., 0.99954423, 0.99882141,
        0.99949278],
       ...,
       [0.99837779, 0.99879413, 0.99954423, ..., 1.        , 0.99799746,
        0.99916644],
       [0.99494244, 0.9992087 , 0.99882141, ..., 0.99799746, 1.        ,
        0.99837501],
       [0.99785025, 0.99895397, 0.99949278, ..., 0.99916644, 0.99837501,
        1.        ]])

In [32]:
# data for testing - for now just take a random sample

sample = tinder_data.sample(5)
sample

,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,drinks_socially,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
user_id,,,,,,,,,,,,,,,,,,,,,
fffe330037003000,21,0,72.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,0
fffe340030003500,27,1,75.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,0
fffe3100300034003400,30,1,70.0,5.0,0,False,False,False,False,True,...,False,False,False,False,False,False,True,False,1,0
fffe3100330039003400,34,1,67.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,False,True,False,0,0
fffe330032003000,26,0,64.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,0

In [33]:
from sklearn.decomposition import TruncatedSVD 
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations(test_user_profile,
                        tinder_data, 
                        number_recommendations=20):

    # get the gender of the user
    test_profile_gender = list(test_profile.sex)[0]

    if test_profile_gender == 1:
        gender_preference = 0
    else:
        gender_preference = 1
    
    # get the tinder data of the opposite 
    td = tinder_data[tinder_data.sex == gender_preference]
    
    # Apply SVD to the training data
    svd = TruncatedSVD(n_components=20) 
    # this is a matrix of all the profiles of the opposite gender
    tinder_profiles_matrix = svd.fit_transform(td) 
    
    # we want to find profiles that are similar to the user
    # first we apply SVD
    test_profile_matrix = svd.transform(test_user_profile) 
    # then calculate the cosine similarity between the user's profile and all other profiles of the opposite gender
    cosine_sim_new = cosine_similarity(test_profile_matrix, tinder_profiles_matrix)

    # convert the scores and select the top N
    scores = pd.DataFrame(cosine_sim_new.transpose())
    scores_ordered = scores.sort_values(by=[0], ascending=False)

    # get the index for top n
    users_index = list(scores_ordered.head(number_recommendations).index)

    # get the user names of the top 
    tinder_data_manipulated = td.reset_index()
    user_ids = list(tinder_data_manipulated[tinder_data_manipulated.index.isin(users_index)].user_id)

    return user_ids

In [34]:
test_profile = pd.DataFrame(sample.iloc[0]).transpose()
test_profile

,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,drinks_socially,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
fffe330037003000,21,0,72.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,0

In [36]:
user_ids = get_recommendations(test_profile, tinder_data)
user_ids

['fffe310030003900',
 'fffe310038003600',
 'fffe340031003700',
 'fffe340031003900',
 'fffe340032003300',
 'fffe350034003800',
 'fffe350035003500',
 'fffe380033003500',
 'fffe380036003100',
 'fffe380036003300',
 'fffe390031003400',
 'fffe3100300031003100',
 'fffe3100300035003800',
 'fffe3100310031003900',
 'fffe3100320032003400',
 'fffe3100330030003100',
 'fffe3100330035003600',
 'fffe3100330038003600',
 'fffe3100340039003000',
 'fffe3100380036003800']

In [37]:
# read the raw data and get the profiles for the test user:

tinder_data_raw = pd.read_csv("../../03Lecture/data/tinder_data.csv")

tinder_data_raw[tinder_data_raw.user_id.isin(user_ids)]

,user_id,username,age,status,sex,orientation,drinks,drugs,height,job,location,pets,smokes,language,new_languages,body_profile,education_level,dropped_out,bio,location_preference
108,fffe310030003900,William Charette,22,single,m,straight,socially,sometimes,70.0,medicine / health,"san francisco, california",likes dogs,no,"english (fluently), russian (fluently)",not interested,athletic,3.0,no,to be honest i don't like this summary thing b...,same city
185,fffe310038003600,Donald Leon,20,single,m,straight,socially,sometimes,70.0,construction / craftsmanship,"berkeley, california",likes dogs and likes cats,no,english (fluently),not interested,thin,3.0,no,my name is alex i would describe myself as you...,same city
416,fffe340031003700,Cory Campbell,22,single,m,straight,socially,sometimes,72.0,banking / financial / real estate,"berkeley, california",likes dogs and dislikes cats,no,"english (fluently), spanish (poorly), other (o...",interested,athletic,2.0,no,"hit me up if you wanna get to know a chill, do...",same city
418,fffe340031003900,Terence Paul,21,single,m,straight,socially,sometimes,72.0,sales / marketing / biz dev,"emeryville, california",likes dogs and dislikes cats,sometimes,"english (fluently), spanish (poorly)",interested,athletic,2.0,no,"my name is rodney. 20 years old, born and rais...",anywhere
422,fffe340032003300,Carl Sanchez,20,single,m,straight,socially,sometimes,71.0,student,"berkeley, california",likes dogs and has cats,no,"english (fluently), italian (fluently), arabic...",interested,average,2.0,no,i am a student. i spend my time playing in ban...,same city
547,fffe350034003800,Jeremy Thaniel,21,single,m,straight,socially,sometimes,75.0,student,"moraga, california",likes dogs and likes cats,sometimes,"english (fluently), spanish (poorly)",interested,average,4.0,no,i'm hope.,same city
554,fffe350035003500,James Rains,23,single,m,straight,socially,sometimes,75.0,education / academia,"mountain view, california",likes dogs and likes cats,no,"english, german (fluently), spanish (okay)",somewhat interested,fit,3.0,no,"i'm big-hearted, fun-loving, and upbeat. i'm o...",same city
834,fffe380033003500,Robert Jacquez,22,single,m,straight,socially,never,71.0,sales / marketing / biz dev,"san francisco, california",likes dogs and has cats,no,"english (fluently), c++ (okay), japanese (poorly)",interested,skinny,2.0,no,"man, you never realize how hard these things a...",same state
860,fffe380036003100,Ryan Burnett,21,single,m,straight,socially,sometimes,70.0,student,"menlo park, california",likes dogs and has cats,no,"english (fluently), spanish (poorly), russian ...",interested,thin,2.0,no,i'm a cool dude. i like some things-- i don't ...,same city
862,fffe380036003300,Jesse Little,21,single,m,straight,socially,never,70.0,student,"berkeley, california",likes dogs,no,"english (fluently), chinese (poorly)",interested,athletic,2.0,no,"hi, i go to school at uc berkeley. i am a fun...",same state
913,fffe390031003400,John Ramp,22,single,m,straight,socially,never,73.0,education / academia,"berkeley, california",likes dogs,no,english,not interested,average,3.0,no,hmmm... well i'm pretty chill and i like to he...,same state
1010,fffe3100300031003100,Leonard Browder,21,single,m,straight,socially,never,72.0,student,"walnut creek, california",likes dogs and likes cats,no,english (poorly),interested,average,2.0,no,"i'm just a guy that loves art, video games, an...",same city
1057,fffe3100300035003800,Michael Lechner,22,single,m,straight,socially,sometimes,72.0,computer / hardware / software,"benicia, california",likes dogs and has cats,no,"english (fluently), spanish (poorly)",interested,a little extra,2.0,no,"hmmm, to summarize myself... i am laid back an...",same state
1118,fffe3100310031003900,Willie Roach,22,single,m,straight,socially,sometimes,73.0,other,"fairfax, california",likes dogs and likes cats,no,"english, spanish (okay)",somewhat interested,skinny,2.0,no,bwah,same state
1223,fffe3100320032003400,Brian Davis,21,single,m,straight,socially,never,70.0,medicine / health,"oakland, california",likes dogs and likes cats,no,"english (poorly), gujarati (fluently), ancient...",interested,athletic,4.0,no,"well my name's ray, if you didn't figure that ...",same city
1300,fffe3100330030003100,Andrew Tully,21,single,m,straight,socially,sometimes,70.0,artistic / musical / writer,"berkeley, california",likes dogs and has cats,no,"english (fluently), french (poorly)",interested,average,2.0,no,"well hmmm, my life currently revolves around m...",same city
1355,fffe3100330035003600,Bryan Felmet,22,single,m,straight,socially,sometimes,72.0,artistic / musical / writer,"san francisco, california",has dogs and likes cats,no,"english (fluently), spanish (fluently)",not interested,athletic,3.0,no,i decided to do this one 'key words' style: 2...,anywhere
1385,fffe3100330038003600,Raul Mcdade,21,single,m,straight,socially,sometimes,70.0,other,"san francisco, california",likes dogs,no,english (fluently),not interested,average,2.0,no,me? i'm winging it. i'm just a dude to be comp...,same state
1489,fffe3100340039003000,Andrew Kane,21,single,m,straight,socially,sometimes,70.0,other,"berkeley, california",likes dogs and likes cats,yes,"english (fluently), french (poorly)",interested,average,2.0,no,"hey there. my name is jake, i'm a really easy-...",same city
1867,fffe3100380036003800,Robert Lewis,22,single,m,straight,socially,never,74.0,banking / financial / real estate,"san rafael, california",likes dogs and likes cats,no,"english (fluently), farsi (fluently), spanish ...",interested,fit,3.0,no,"sociable, honest, and very straightforward. i'...",same city

In [ ]:
# apply any known personal preference of the user

In [ ]:
# what do we think about the recommendations?

In [99]:
# try for another user
test_profile = pd.DataFrame(sample.iloc[3]).transpose()
print(test_profile)
user_ids = get_recommendations(test_profile, tinder_data)

                     age sex height education_level dropped_out  \
fffe3100300035003300  29   0   60.0             4.0           0

                     drinks_desperately drinks_not at all drinks_often  \
fffe3100300035003300              False             False        False

                     drinks_rarely drinks_socially  ...  \
fffe3100300035003300         False            True  ...

                     body_profile_overweight body_profile_rather not say  \
fffe3100300035003300                   False                       False

                     body_profile_skinny body_profile_thin  \
fffe3100300035003300               False             False

                     body_profile_used up new_languages_interested  \
fffe3100300035003300                False                    False

                     new_languages_not interested  \
fffe3100300035003300                        False

                     new_languages_somewhat interested likes_dog likes_cats
fffe3100300035003300                              True         1          0

[1 rows x 57 columns]

In [100]:
tinder_data_raw[tinder_data_raw.user_id.isin(user_ids)]

,user_id,username,age,status,sex,orientation,drinks,drugs,height,job,location,pets,smokes,language,new_languages,body_profile,education_level,dropped_out,bio,location_preference
248,fffe320034003900,Ralph Boyd,34,single,m,straight,socially,never,69.0,executive / management,"mountain view, california",likes dogs,no,english,not interested,athletic,3.0,no,"new to this site, just checking it out!",same city
290,fffe320039003100,Fidel Tassin,34,single,m,straight,socially,never,68.0,banking / financial / real estate,"san francisco, california",likes dogs,no,"english (fluently), spanish (fluently), chines...",somewhat interested,athletic,3.0,no,i'm as american as you can get without actuall...,same city
396,fffe330039003700,Demarcus Kinkel,34,single,m,straight,rarely,never,69.0,executive / management,"san bruno, california",likes dogs and likes cats,no,"english (fluently), french (fluently), urdu (f...",somewhat interested,athletic,4.0,no,i love to try new things and i really love to ...,same city
448,fffe340034003900,Freddie Lefebvre,35,single,m,straight,socially,never,73.0,science / tech / engineering,"palo alto, california",likes dogs,no,"english (fluently), french (poorly), german (p...",interested,a little extra,5.0,no,"cities i have called home, from 2005 on: genev...",same city
546,fffe350034003700,Frank Spooner,33,single,m,straight,socially,never,70.0,medicine / health,"berkeley, california",likes dogs,no,"english, spanish (okay), french (poorly), swah...",interested,athletic,4.0,no,berkeley man kisses boring online dating goodb...,same state
787,fffe370038003800,Dion Zito,32,single,m,straight,socially,never,66.0,hospitality / travel,"san francisco, california",likes dogs and likes cats,no,"english (okay), english (okay), vietnamese (fl...",somewhat interested,average,3.0,no,"i am a bit quiet ,honest and hardworking.",same city
840,fffe380034003100,William Zenisek,35,single,m,straight,socially,never,74.0,computer / hardware / software,"san francisco, california",likes dogs and likes cats,no,"english (fluently), french (poorly)",interested,athletic,4.0,no,i'm a lifelong east coaster somehow loving sf....,same state
864,fffe380036003500,Raymond Demski,35,single,m,straight,socially,never,73.0,hospitality / travel,"burlingame, california",likes dogs,no,english,not interested,athletic,3.0,no,"i'm a fun, kind, healthy person who loves to t...",same city
904,fffe390030003500,Rodney Church,33,single,m,straight,socially,never,72.0,science / tech / engineering,"san francisco, california",likes dogs and likes cats,no,"english (fluently), french (okay), spanish (okay)",somewhat interested,athletic,4.0,no,"i like fascinating, passionate, creative peopl...",same city
1095,fffe3100300039003600,John Moore,31,single,m,straight,socially,never,66.0,law / legal services,"san francisco, california",likes dogs,no,english,not interested,average,4.0,no,i've been living in san francisco since making...,same city
1106,fffe3100310030003700,Harry Lee,31,single,m,straight,socially,never,65.0,science / tech / engineering,"menlo park, california",likes dogs and likes cats,no,"english (fluently), portuguese (fluently), hin...",somewhat interested,fit,4.0,no,"i heart the letter s (silly, serious, sunny, s...",same city
1294,fffe3100320039003500,James Sanchez,32,single,m,straight,often,never,65.0,executive / management,"san francisco, california",likes dogs,no,"english (fluently), spanish (fluently), hindi ...",interested,athletic,4.0,no,moved to the bay area a couple of years ago af...,same state
1335,fffe3100330033003600,Jose Garcia,33,single,m,straight,socially,never,68.0,education / academia,"san francisco, california",likes dogs and likes cats,no,"english (fluently), c++ (okay)",somewhat interested,a little extra,4.0,no,i'm a san francisco native. i'm a classically ...,same city
1336,fffe3100330033003700,Jack Eby,32,single,m,straight,socially,never,69.0,computer / hardware / software,"san francisco, california",likes dogs,no,"english (fluently), hindi (fluently)",not interested,athletic,5.0,no,i moved to sf from dc two years ago. it's been...,anywhere
1348,fffe3100330034003900,Jose Trammell,34,single,m,straight,socially,never,69.0,medicine / health,"emeryville, california",likes dogs and dislikes cats,no,"english, spanish",not interested,athletic,4.0,no,"not perfect by any means, but first word that ...",same state
1493,fffe3100340039003400,Edward Craft,31,single,m,straight,socially,never,67.0,banking / financial / real estate,"san francisco, california",has dogs,no,"english, spanish, hebrew",not interested,athletic,4.0,no,"i love to be outside: running on trails, looki...",same city
1541,fffe3100350034003200,Dean Hollingsworth,34,single,m,straight,socially,never,68.0,executive / management,"el cerrito, california",likes dogs and likes cats,no,english,not interested,athletic,4.0,no,"i smile a lot. not because i'm crazy, but beca...",same city
1635,fffe3100360033003600,Walter Logan,31,single,m,straight,socially,never,67.0,banking / financial / real estate,"san mateo, california",likes dogs,no,"english (fluently), chinese (poorly)",interested,athletic,4.0,no,"when i was a kid, i spent hours and hours prac...",same city
1875,fffe3100380037003600,James Amos,33,single,m,straight,not at all,never,68.0,banking / financial / real estate,"san leandro, california",likes dogs,no,"english (fluently), chinese (okay)",somewhat interested,average,4.0,no,so i've never really been good at describing m...,same city
1950,fffe3100390035003100,Antonio Gonyea,33,single,m,straight,socially,never,70.0,sales / marketing / biz dev,"san francisco, california",likes dogs and likes cats,no,english,not interested,athletic,4.0,yes,i'm a strange mix of things. i think a lot and...,same city