In [13]:
import pandas as pd

In [21]:
tinder_data = pd.read_csv("../data/tinder_data_prepared.csv")

In [22]:
# check shape
tinder_data.shape

(1321, 58)

In [23]:
# check info
tinder_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1321 entries, 0 to 1320
Data columns (total 58 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   user_id                                1321 non-null   object
 1   age                                    1321 non-null   int64
 2   sex                                    1321 non-null   int64
 3   height                                 1321 non-null   float64
 4   education_level                        1321 non-null   float64
 5   dropped_out                            1321 non-null   int64
 6   drinks_desperately                     1321 non-null   bool
 7   drinks_not at all                      1321 non-null   bool
 8   drinks_often                           1321 non-null   bool
 9   drinks_rarely                          1321 non-null   bool
 10  drinks_socially                        1321 non-null   bool
 11  drinks_very often                      1321 non-null   bool
 12  drugs_never                            1321 non-null   bool
 13  drugs_often                            1321 non-null   bool
 14  drugs_sometimes                        1321 non-null   bool
 15  job_artistic / musical / writer        1321 non-null   bool
 16  job_banking / financial / real estate  1321 non-null   bool
 17  job_clerical / administrative          1321 non-null   bool
 18  job_computer / hardware / software     1321 non-null   bool
 19  job_construction / craftsmanship       1321 non-null   bool
 20  job_education / academia               1321 non-null   bool
 21  job_entertainment / media              1321 non-null   bool
 22  job_executive / management             1321 non-null   bool
 23  job_hospitality / travel               1321 non-null   bool
 24  job_law / legal services               1321 non-null   bool
 25  job_medicine / health                  1321 non-null   bool
 26  job_military                           1321 non-null   bool
 27  job_other                              1321 non-null   bool
 28  job_political / government             1321 non-null   bool
 29  job_rather not say                     1321 non-null   bool
 30  job_retired                            1321 non-null   bool
 31  job_sales / marketing / biz dev        1321 non-null   bool
 32  job_science / tech / engineering       1321 non-null   bool
 33  job_student                            1321 non-null   bool
 34  job_transportation                     1321 non-null   bool
 35  job_unemployed                         1321 non-null   bool
 36  smokes_no                              1321 non-null   bool
 37  smokes_sometimes                       1321 non-null   bool
 38  smokes_trying to quit                  1321 non-null   bool
 39  smokes_when drinking                   1321 non-null   bool
 40  smokes_yes                             1321 non-null   bool
 41  body_profile_a little extra            1321 non-null   bool
 42  body_profile_athletic                  1321 non-null   bool
 43  body_profile_average                   1321 non-null   bool
 44  body_profile_curvy                     1321 non-null   bool
 45  body_profile_fit                       1321 non-null   bool
 46  body_profile_full figured              1321 non-null   bool
 47  body_profile_jacked                    1321 non-null   bool
 48  body_profile_overweight                1321 non-null   bool
 49  body_profile_rather not say            1321 non-null   bool
 50  body_profile_skinny                    1321 non-null   bool
 51  body_profile_thin                      1321 non-null   bool
 52  body_profile_used up                   1321 non-null   bool
 53  new_languages_interested               1321 non-null   bool
 54  new_languages_not interested           1321 non-null   bool
 55  new_languages_somewhat interested      1321 non-null   bool
 56  likes_dog                              1321 non-null   int64
 57  likes_cats                             1321 non-null   int64
dtypes: bool(50), float64(2), int64(5), object(1)
memory usage: 147.2+ KB

In [24]:
tinder_data.head()

,user_id,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
0,fffe31003000,28,1,62.0,4.0,0,False,False,False,False,...,False,False,False,False,True,False,True,False,1,1
1,fffe31003200,24,0,65.0,3.0,0,False,False,False,False,...,False,False,False,False,False,True,False,False,1,1
2,fffe31003300,29,1,73.0,3.0,0,False,False,False,False,...,False,False,False,False,False,False,True,False,1,1
3,fffe31003400,33,0,65.0,4.0,0,False,False,False,False,...,False,False,False,False,False,False,True,False,0,0
4,fffe31003500,39,0,65.0,4.0,0,False,False,True,False,...,False,False,False,False,False,False,True,False,1,0

In [28]:
# set index
tinder_data = tinder_data.set_index("user_id")

In [29]:
tinder_data.head()

,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,drinks_socially,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
user_id,,,,,,,,,,,,,,,,,,,,,
fffe31003000,28,1,62.0,4.0,0,False,False,False,False,False,...,False,False,False,False,True,False,True,False,1,1
fffe31003200,24,0,65.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,1
fffe31003300,29,1,73.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,False,True,False,1,1
fffe31003400,33,0,65.0,4.0,0,False,False,False,False,True,...,False,False,False,False,False,False,True,False,0,0
fffe31003500,39,0,65.0,4.0,0,False,False,True,False,False,...,False,False,False,False,False,False,True,False,1,0

In [30]:
from sklearn.decomposition import TruncatedSVD 

# Apply SVD to the training data
svd = TruncatedSVD(n_components=20) 
# this is a matrix of all the profiles of the opposite gender
tinder_profiles_matrix = svd.fit_transform(tinder_data)

tinder_profiles_matrix

array([[ 6.81246999e+01,  1.84406016e+00, -3.91469382e-01, ...,
        -8.54875364e-02, -1.03044108e-01,  2.65165081e-01],
       [ 6.93214169e+01, -2.97741372e+00, -8.07475208e-01, ...,
        -6.15140878e-02, -4.86716924e-02, -6.92653765e-02],
       [ 7.86335479e+01, -1.51333216e+00, -1.09259725e-01, ...,
        -4.88736702e-02, -1.28916280e-01,  5.53051265e-02],
       ...,
       [ 7.90137430e+01, -6.12506336e-01, -1.27343442e-01, ...,
        -5.38158095e-02,  4.25567156e-01, -1.14167111e-01],
       [ 7.29681475e+01, -4.64923839e+00,  7.18356832e-01, ...,
         6.64198638e-02,  4.28522238e-02, -1.52673123e-01],
       [ 7.63881860e+01, -1.65619874e+00, -4.76758297e-02, ...,
        -5.65258579e-01,  5.79961073e-01,  4.01367172e-01]])

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tinder_profiles_matrix)

array([[1.        , 0.99646088, 0.99817833, ..., 0.99837779, 0.99494244,
        0.99785025],
       [0.99646088, 1.        , 0.99942894, ..., 0.99879413, 0.9992087 ,
        0.99895397],
       [0.99817833, 0.99942894, 1.        , ..., 0.99954423, 0.99882141,
        0.99949278],
       ...,
       [0.99837779, 0.99879413, 0.99954423, ..., 1.        , 0.99799746,
        0.99916644],
       [0.99494244, 0.9992087 , 0.99882141, ..., 0.99799746, 1.        ,
        0.99837501],
       [0.99785025, 0.99895397, 0.99949278, ..., 0.99916644, 0.99837501,
        1.        ]])

In [33]:
from sklearn.decomposition import TruncatedSVD 
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations(test_user_profile,
                        tinder_data, 
                        number_recommendations=20):

    # get the gender of the user
    test_profile_gender = list(test_profile.sex)[0]

    if test_profile_gender == 1:
        gender_preference = 0
    else:
        gender_preference = 1
    
    # get the tinder data of the opposite 
    td = tinder_data[tinder_data.sex == gender_preference]
    
    # Apply SVD to the training data
    svd = TruncatedSVD(n_components=20) 
    # this is a matrix of all the profiles of the opposite gender
    tinder_profiles_matrix = svd.fit_transform(td) 
    
    # we want to find profiles that are similar to the user
    # first we apply SVD
    test_profile_matrix = svd.transform(test_user_profile) 
    # then calculate the cosine similarity between the user's profile and all other profiles of the opposite gender
    cosine_sim_new = cosine_similarity(test_profile_matrix, tinder_profiles_matrix)

    # convert the scores and select the top N
    scores = pd.DataFrame(cosine_sim_new.transpose())
    scores_ordered = scores.sort_values(by=[0], ascending=False)

    # get the index for top n
    users_index = list(scores_ordered.head(number_recommendations).index)

    # get the user names of the top 
    tinder_data_manipulated = td.reset_index()
    user_ids = list(tinder_data_manipulated[tinder_data_manipulated.index.isin(users_index)].user_id)

    return user_ids

In [ ]:
# data for testing - for now just take a random sample

sample = tinder_data.sample(5)
sample

In [34]:
test_profile = pd.DataFrame(sample.iloc[0]).transpose()
test_profile

,age,sex,height,education_level,dropped_out,drinks_desperately,drinks_not at all,drinks_often,drinks_rarely,drinks_socially,...,body_profile_overweight,body_profile_rather not say,body_profile_skinny,body_profile_thin,body_profile_used up,new_languages_interested,new_languages_not interested,new_languages_somewhat interested,likes_dog,likes_cats
fffe330037003000,21,0,72.0,3.0,0,False,False,False,False,True,...,False,False,False,False,False,True,False,False,1,0

In [41]:
user_ids = get_recommendations(test_profile, tinder_data, number_recommendations=100)
user_ids

['fffe38003900',
 'fffe39003800',
 'fffe310030003900',
 'fffe310033003000',
 'fffe310035003200',
 'fffe310036003000',
 'fffe310037003400',
 'fffe310038003600',
 'fffe310039003100',
 'fffe320030003600',
 'fffe320031003400',
 'fffe320032003600',
 'fffe320034003000',
 'fffe320036003100',
 'fffe330032003400',
 'fffe330033003800',
 'fffe330034003300',
 'fffe330035003100',
 'fffe330037003400',
 'fffe330037003500',
 'fffe340031003700',
 'fffe340031003900',
 'fffe340032003300',
 'fffe340035003500',
 'fffe340038003700',
 'fffe350030003000',
 'fffe350031003500',
 'fffe350032003000',
 'fffe350032003200',
 'fffe350034003800',
 'fffe350035003500',
 'fffe350035003700',
 'fffe360030003800',
 'fffe360032003500',
 'fffe360034003500',
 'fffe360035003200',
 'fffe360036003400',
 'fffe360038003500',
 'fffe360039003800',
 'fffe370039003100',
 'fffe370039003300',
 'fffe380033003500',
 'fffe380035003700',
 'fffe380036003000',
 'fffe380036003100',
 'fffe380036003300',
 'fffe390031003400',
 'fffe390031003700',
 'fffe3100300030003200',
 'fffe3100300031003100',
 'fffe3100300033003900',
 'fffe3100300035003800',
 'fffe3100300037003600',
 'fffe3100310031003900',
 'fffe3100310035003000',
 'fffe3100310036003100',
 'fffe3100310039003400',
 'fffe3100320032003200',
 'fffe3100320032003400',
 'fffe3100320033003500',
 'fffe3100320036003800',
 'fffe3100320038003700',
 'fffe3100320039003900',
 'fffe3100330030003100',
 'fffe3100330032003300',
 'fffe3100330033003200',
 'fffe3100330035003600',
 'fffe3100330037003800',
 'fffe3100330038003000',
 'fffe3100330038003600',
 'fffe3100330038003800',
 'fffe3100330038003900',
 'fffe3100340030003400',
 'fffe3100340032003300',
 'fffe3100340032003800',
 'fffe3100340033003200',
 'fffe3100340034003600',
 'fffe3100340039003000',
 'fffe3100350031003700',
 'fffe3100350033003400',
 'fffe3100350035003700',
 'fffe3100350039003600',
 'fffe3100360030003800',
 'fffe3100360031003200',
 'fffe3100360032003100',
 'fffe3100360033003500',
 'fffe3100360035003000',
 'fffe3100360038003600',
 'fffe3100370030003500',
 'fffe3100370031003100',
 'fffe3100370032003100',
 'fffe3100370032003400',
 'fffe3100370034003000',
 'fffe3100370035003900',
 'fffe3100370039003700',
 'fffe3100380036003800',
 'fffe3100380038003200',
 'fffe3100380038003700',
 'fffe3100390036003400',
 'fffe3100390039003000']

In [42]:
# read the raw data and get the profiles for the test user:

tinder_data_raw = pd.read_csv("../data/tinder_data_filtered.csv")

tinder_data_raw[tinder_data_raw.user_id.isin(user_ids)]

,user_id,username,age,sex,drinks,drugs,height,job,pets,smokes,language,new_languages,body_profile,education_level,dropped_out,bio,cleaned_bio
58,fffe38003900,Michael Dolezal,20,m,rarely,never,72.0,medicine / health,has dogs,no,"english (fluently), portuguese (fluently), spa...",somewhat interested,jacked,2.0,no,"1. love to workout, staying healthy and active...",love workout stay healthy active soccer passio...
66,fffe39003800,Roy Burnell,22,m,socially,sometimes,69.0,other,likes dogs and likes cats,yes,"english (fluently), spanish (okay)",somewhat interested,fit,3.0,no,hi,hi
71,fffe310030003900,William Charette,22,m,socially,sometimes,70.0,medicine / health,likes dogs,no,"english (fluently), russian (fluently)",not interested,athletic,3.0,no,to be honest i don't like this summary thing b...,honest like summary thing know oh guess let st...
87,fffe310033003000,Jason Cifelli,20,m,not at all,never,71.0,student,likes dogs and likes cats,no,english (fluently),not interested,a little extra,2.0,no,wants to enjoy life to its fullest :),want enjoy life full
108,fffe310035003200,Michael Berryman,22,m,often,sometimes,72.0,artistic / musical / writer,likes dogs and likes cats,when drinking,english (fluently),not interested,athletic,2.0,no,"i'm an easygoing guy, not really looking for a...",easygoing guy look relationship right drummer ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,fffe3100380036003800,Robert Lewis,22,m,socially,never,74.0,banking / financial / real estate,likes dogs and likes cats,no,"english (fluently), farsi (fluently), spanish ...",interested,fit,3.0,no,"sociable, honest, and very straightforward. i'...",sociable honest straightforward travel result ...
1249,fffe3100380038003200,Donald Christie,24,m,socially,never,76.0,sales / marketing / biz dev,likes dogs,no,"english, spanish (okay)",somewhat interested,athletic,3.0,no,i am brand new to the bay area and am looking ...,brand new bay area look venture recently move ...
1252,fffe3100380038003700,Kurt Romano,23,m,socially,never,70.0,sales / marketing / biz dev,likes dogs and likes cats,when drinking,"english (fluently), spanish (poorly), other (o...",interested,thin,3.0,no,"i love company, but i'm also really introspect...",love company introspective make sense favorite...
1299,fffe3100390036003400,John Solomons,22,m,socially,never,71.0,computer / hardware / software,likes dogs and likes cats,no,"english (fluently), croatian (okay), czech (fl...",somewhat interested,fit,2.0,no,pursuing the happiness in silicon valley. co-f...,pursue happiness silicon valley co founder pro...
1316,fffe3100390039003000,Scott Grady,19,m,socially,never,73.0,student,has dogs and likes cats,no,"english (fluently), spanish (poorly), chinese ...",interested,average,3.0,no,"hmm, i'd like to say i'm ambitious at almost e...",hmm like ambitious aspect try like good food t...

In [ ]:
# apply any known personal preference of the user

In [ ]:
# what do we think about the recommendations?

In [43]:
# try for another user
test_profile = pd.DataFrame(sample.iloc[3]).transpose()
print(test_profile)
user_ids = get_recommendations(test_profile, tinder_data)

                     age sex height education_level dropped_out  \
fffe3100330039003400  34   1   67.0             3.0           0

                     drinks_desperately drinks_not at all drinks_often  \
fffe3100330039003400              False             False        False

                     drinks_rarely drinks_socially  ...  \
fffe3100330039003400         False            True  ...

                     body_profile_overweight body_profile_rather not say  \
fffe3100330039003400                   False                       False

                     body_profile_skinny body_profile_thin  \
fffe3100330039003400               False             False

                     body_profile_used up new_languages_interested  \
fffe3100330039003400                False                    False

                     new_languages_not interested  \
fffe3100330039003400                         True

                     new_languages_somewhat interested likes_dog likes_cats
fffe3100330039003400                             False         0          0

[1 rows x 57 columns]

In [44]:
tinder_data_raw[tinder_data_raw.user_id.isin(user_ids)]

,user_id,username,age,sex,drinks,drugs,height,job,pets,smokes,language,new_languages,body_profile,education_level,dropped_out,bio,cleaned_bio
3,fffe31003400,Claudine Shreve,33,f,socially,never,65.0,other,has dogs,no,"english, spanish (fluently)",not interested,a little extra,4.0,no,i'm a mixed bag of nuts! i'm outgoing yet shy ...,mixed bag nut outgoing shy meet people grow sf...
27,fffe34003900,Carolyn Smith,36,f,not at all,sometimes,70.0,other,likes dogs and has cats,no,"english (fluently), spanish (okay)",somewhat interested,a little extra,4.0,no,"unique, intelligent, creative, caring, counter...",unique intelligent creative caring counter cul...
116,fffe310036003700,Helen Hayden,33,f,socially,never,69.0,entertainment / media,has dogs,no,english (fluently),not interested,athletic,3.0,no,i'm looking for someone who inspires me. someo...,look inspire wake get excited need understand ...
199,fffe320039003800,Dorothy Williams,33,f,socially,never,67.0,other,has dogs,no,english,not interested,fit,3.0,no,"i love witty banter, sangria, road trips and f...",love witty banter sangria road trip film like ...
208,fffe330030003900,Ruth Foley,34,f,socially,never,64.0,medicine / health,likes dogs,no,"english (fluently), spanish (fluently)",not interested,fit,3.0,no,"i moved to the city around 8 years ago and, in...",move city year ago inspire sf foodie culture f...
248,fffe330037003300,Kristina Miller,34,f,socially,never,65.0,sales / marketing / biz dev,has dogs,no,"english (fluently), spanish (okay)",somewhat interested,athletic,3.0,no,purebred cali girl! born and raised in nor cal...,purebre cali girl bear raise cal move love sf ...
317,fffe340037003300,Mary Hickok,31,f,socially,sometimes,62.0,science / tech / engineering,likes dogs and has cats,yes,english,not interested,used up,4.0,no,"potty-mouthed and cat-obsessed, what more coul...",potty mouthed cat obsess ask
346,fffe350032003100,Regina Johnson,36,f,socially,never,68.0,medicine / health,likes dogs and has cats,no,"english (fluently), spanish (fluently)",not interested,fit,4.0,no,"loyal to family, friends, working hard, playin...",loyal family friend work hard play like year o...
442,fffe360037003100,Denise Charriez,36,f,socially,never,70.0,clerical / administrative,likes cats,no,english,not interested,overweight,3.0,no,i'm aggressive! or so i've been told. it puts ...,aggressive tell put people know find hard work...
486,fffe370032003700,Phyllis Winton,33,f,socially,sometimes,65.0,other,has dogs,no,"english (fluently), spanish (poorly)",interested,fit,4.0,no,i like to dance. i like to write. i love my wo...,like dance like write love work expressive art...
552,fffe380032003500,Lisa Miller,35,f,rarely,never,68.0,other,has dogs,no,english,not interested,athletic,3.0,no,i'm a bay area native. i grew up in marin coun...,bay area native grow marin county move seattle...
616,fffe390032003200,Cynthia Wason,35,f,socially,never,68.0,sales / marketing / biz dev,likes dogs,no,english,not interested,thin,3.0,no,"witty, loyal, outgoing, independent, kind-hear...",witty loyal outgoing independent kind hearted ...
660,fffe390039003000,Agnes Garland,33,f,socially,never,66.0,other,has dogs,no,"english, spanish (poorly)",interested,athletic,3.0,no,"i am a sports loving, eco-conscious adventurou...",sport loving eco conscious adventurous woman s...
809,fffe3100320031003700,Erin Lancaster,32,f,socially,never,62.0,medicine / health,has cats,when drinking,english,not interested,average,3.0,no,"i am originally from the east coast, but i hav...",originally east coast live bay area year suppo...
889,fffe3100330032003900,Joyce Stone,31,f,socially,never,63.0,medicine / health,has dogs,yes,english,not interested,curvy,2.0,no,i'm not really sure what i'm going to find or ...,sure go find go meet life exciting thing adven...
916,fffe3100330036003800,Lynn Perryman,32,f,socially,never,64.0,law / legal services,likes dogs and has cats,no,"english (fluently), chinese (fluently)",not interested,athletic,4.0,no,my personality can best be described through m...,personality well describe friend assessment re...
973,fffe3100340034003800,Eula Hammers,31,f,socially,never,62.0,entertainment / media,has dogs,no,"english (fluently), tagalog (poorly)",interested,curvy,3.0,no,i'm new & haven't had any time to fill in all ...,new time fill information whoa realize long fi...
1105,fffe3100360036003500,Rachel Foote,33,f,socially,never,65.0,entertainment / media,likes dogs and has cats,sometimes,english (fluently),not interested,average,3.0,no,the basics: i grew up in southern california (...,basic grow southern california hold sf year lo...
1156,fffe3100370033003800,Mary Rodriguez,36,f,not at all,never,70.0,medicine / health,likes dogs and has cats,no,english,not interested,fit,4.0,no,i have lots to give and am happy to spoil the ...,lot happy spoil right person definitely picky ...
1225,fffe3100380034003800,Delores Davis,31,f,socially,never,63.0,medicine / health,has dogs and has cats,no,english (fluently),not interested,curvy,4.0,no,i am a small animal veterinarian. in my free t...,small animal veterinarian free time spend take...